package webplatform.model.entity;

// default package
// Generated May 9, 2017 11:21:55 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Aluno generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ALUNO")
public class Aluno implements java.io.Serializable {

	private Long id;
	private Professor professor;
	private Pais pais;
	private String nome;
	private String sobrenome;
	private String email;
	private String genero;
	private String password;
	private Set<Convite> convites = new HashSet<Convite>();
	private Set<ExercicioAluno> exercicioAlunos = new HashSet<ExercicioAluno>();

	public Aluno() {
	}

	public Aluno(Long id) {
		this.id = id;
	}

	public Aluno(Long id, Professor professor, String nome, String email, String password, Set<Convite> convites,
			Set<ExercicioAluno> exercicioAlunos, String sobrenome, String genero, Pais pais) {
		this.id = id;
		this.professor = professor;
		this.nome = nome;
		this.email = email;
		this.password = password;
		this.convites = convites;
		this.exercicioAlunos = exercicioAlunos;
		this.sobrenome = sobrenome;
		this.genero = genero;
		this.pais = pais;
	}

	@Id
	@SequenceGenerator(name = "ALUNO_SEQUENCE", sequenceName = "ALUNO_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "ALUNO_SEQUENCE")
	@Column(name = "ID_ALUNO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long idAluno) {
		this.id = idAluno;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PROFESSOR")
	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aluno")
	@JsonIgnore
	public Set<Convite> getConvites() {
		return this.convites;
	}

	public void setConvites(Set<Convite> convites) {
		this.convites = convites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aluno")
	@JsonIgnore
	public Set<ExercicioAluno> getExercicioAlunos() {
		return this.exercicioAlunos;
	}

	public void setExercicioAlunos(Set<ExercicioAluno> exercicioAlunos) {
		this.exercicioAlunos = exercicioAlunos;
	}

	@Column(name = "SOBRENOME", length = 50)
	public String getSobrenome() {
		return sobrenome;
	}

	public void setSobrenome(String sobrenome) {
		this.sobrenome = sobrenome;
	}

	@Column(name = "GENERO", length = 6)
	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

}
