package webplatform.model.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConviteId generated by hbm2java
 */
@Embeddable
public class ConviteId implements java.io.Serializable {

	private Long professor;
	private Long aluno;

	public ConviteId() {
	}

	public ConviteId(Long professor, Long aluno) {
		this.professor = professor;
		this.aluno = aluno;
	}

	@Column(name = "PROFESSOR", nullable = false, precision = 22, scale = 0)
	public Long getProfessor() {
		return this.professor;
	}

	public void setProfessor(Long professor) {
		this.professor = professor;
	}

	@Column(name = "ALUNO", nullable = false, precision = 22, scale = 0)
	public Long getAluno() {
		return this.aluno;
	}

	public void setAluno(Long aluno) {
		this.aluno = aluno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConviteId))
			return false;
		ConviteId castOther = (ConviteId) other;

		return ((this.getProfessor() == castOther.getProfessor()) || (this.getProfessor() != null
				&& castOther.getProfessor() != null && this.getProfessor().equals(castOther.getProfessor())))
				&& ((this.getAluno() == castOther.getAluno()) || (this.getAluno() != null
						&& castOther.getAluno() != null && this.getAluno().equals(castOther.getAluno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProfessor() == null ? 0 : this.getProfessor().hashCode());
		result = 37 * result + (getAluno() == null ? 0 : this.getAluno().hashCode());
		return result;
	}

}
