package webplatform.model.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Exercicio generated by hbm2java
 */
@Entity
@Table(name = "EXERCICIO")
public class Exercicio implements java.io.Serializable {

	private Long idExercicio;
	private Professor professor;
	private Musica musica;
	private String nome;
	private String nivel;
	private int valorNotaMaxima;
	private Byte media;
	private Set<ExercicioAluno> exercicioAlunos = new HashSet<ExercicioAluno>();
	private Set<Questao> questoes = new HashSet<Questao>();

	public Exercicio() {
	}

	public Exercicio(Long idExercicio) {
		this.idExercicio = idExercicio;
	}

	public Exercicio(Long idExercicio, Professor professor, Musica musica, String nome, String nivel,
			int valorNotaMaxima, Byte media, Set<ExercicioAluno> exercicioAlunos, Set<Questao> questoes) {
		this.idExercicio = idExercicio;
		this.professor = professor;
		this.musica = musica;
		this.nome = nome;
		this.nivel = nivel;
		this.valorNotaMaxima = valorNotaMaxima;
		this.media = media;
		this.exercicioAlunos = exercicioAlunos;
		this.questoes = questoes;
	}

	@Id
	@SequenceGenerator(name = "EXERCICIO_SEQUENCE", sequenceName = "EXERCICIO_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "EXERCICIO_SEQUENCE")
	@Column(name = "ID_EXERCICIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdExercicio() {
		return this.idExercicio;
	}

	public void setIdExercicio(Long idExercicio) {
		this.idExercicio = idExercicio;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PROFESSOR")
	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	@OneToOne
	@JoinColumn(name = "MUSICA")
	public Musica getMusica() {
		return this.musica;
	}

	public void setMusica(Musica musica) {
		this.musica = musica;
	}

	@Column(name = "NOME", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "NIVEL", length = 15)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	@Column(name = "VALOR_NOTA_MAXIMA", precision = 2, scale = 0)
	public int getValorNotaMaxima() {
		return this.valorNotaMaxima;
	}

	public void setValorNotaMaxima(int valorNotaMaxima) {
		this.valorNotaMaxima = valorNotaMaxima;
	}

	@Column(name = "MEDIA", precision = 2, scale = 0)
	public Byte getMedia() {
		return this.media;
	}

	public void setMedia(Byte media) {
		this.media = media;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public Set<ExercicioAluno> getExercicioAlunos() {
		return this.exercicioAlunos;
	}

	public void setExercicioAlunos(Set<ExercicioAluno> exercicioAlunos) {
		this.exercicioAlunos = exercicioAlunos;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public Set<Questao> getQuestoes() {
		return this.questoes;
	}

	public void setQuestoes(Set<Questao> questaos) {
		this.questoes = questaos;
	}

}
