package webplatform.model.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ExercicioAlunoResposta generated by hbm2java
 */
@Entity
@Table(name = "EXERCICIO_ALUNO_RESPOSTA")
public class ExercicioAlunoResposta implements java.io.Serializable {

	private Long idExercicioAlunoResposta;
	private Questao questao;
	private Alternativa alternativa;
	private ExercicioAluno exercicioAluno;
	private Integer nota;

	public ExercicioAlunoResposta() {
	}

	public ExercicioAlunoResposta(Long idExercicioAlunoResposta) {
		this.idExercicioAlunoResposta = idExercicioAlunoResposta;
	}

	public ExercicioAlunoResposta(Long idExercicioAlunoResposta, Questao questao, Alternativa alternativa,
			ExercicioAluno exercicioAluno, Integer nota) {
		this.idExercicioAlunoResposta = idExercicioAlunoResposta;
		this.questao = questao;
		this.alternativa = alternativa;
		this.exercicioAluno = exercicioAluno;
		this.nota = nota;
	}

	@Id
	@GenericGenerator(name = "EXERCICIO_ALUNO_RESPOSTA_SEQ", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "EXERCICIO_ALUNO_RESPOSTA_SEQ"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "EXERCICIO_ALUNO_RESPOSTA_SEQ")
	@Column(name = "ID_EXERCICIO_ALUNO_RESPOSTA", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdExercicioAlunoResposta() {
		return this.idExercicioAlunoResposta;
	}

	public void setIdExercicioAlunoResposta(Long idExercicioAlunoResposta) {
		this.idExercicioAlunoResposta = idExercicioAlunoResposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTAO")
	public Questao getQuestao() {
		return this.questao;
	}

	public void setQuestao(Questao questao) {
		this.questao = questao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALTERNATIVA")
	public Alternativa getAlternativa() {
		return this.alternativa;
	}

	public void setAlternativa(Alternativa alternativa) {
		this.alternativa = alternativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXERCICIO_ALUNO")
	public ExercicioAluno getExercicioAluno() {
		return this.exercicioAluno;
	}

	public void setExercicioAluno(ExercicioAluno exercicioAluno) {
		this.exercicioAluno = exercicioAluno;
	}

	@Column(name = "NOTA", precision = 2, scale = 0)
	public Integer getNota() {
		return this.nota;
	}

	public void setNota(Integer nota) {
		this.nota = nota;
	}

}
