package webplatform.model.entity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Exercicio generated by hbm2java
 */
@Entity
@Table(name = "EXERCICIO")
public class Exercicio implements java.io.Serializable {

	private Long idExercicio;
	private Professor professor;
	private Musica musica;
	// TODO: remover atributo nome
	private String nome;
	private String nivel;
	private String writingQuestao;
	private int valorNotaMaxima;
	private Byte media;
	private Integer totalPosts;
	private Set<ExercicioAluno> exercicioAlunos = new HashSet<ExercicioAluno>();
	private Set<Questao> questoes = new HashSet<Questao>();
	private List<Imagem> imagens = new ArrayList<Imagem>();
	private List<GrammarDefinicao> grammarDefinicoes = new ArrayList<GrammarDefinicao>();
	private List<ReadingQuestao> readingQuestoes = new ArrayList<ReadingQuestao>();
	private List<PronunciationQuestao> pronunciationQuestoes = new ArrayList<PronunciationQuestao>();

	public Exercicio() {
	}

	public Exercicio(Long idExercicio) {
		this.idExercicio = idExercicio;
	}

	public Exercicio(Long idExercicio, Professor professor, Musica musica, String nome, String nivel,
			int valorNotaMaxima, Byte media, Set<ExercicioAluno> exercicioAlunos, Set<Questao> questoes,
			ArrayList<Imagem> imagens) {
		this.idExercicio = idExercicio;
		this.professor = professor;
		this.musica = musica;
		this.nome = nome;
		this.nivel = nivel;
		this.valorNotaMaxima = valorNotaMaxima;
		this.media = media;
		this.exercicioAlunos = exercicioAlunos;
		this.questoes = questoes;
		this.imagens = imagens;
	}

	@Id
	@GenericGenerator(name = "EXERCICIO_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "EXERCICIO_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "EXERCICIO_SEQUENCE")
	@Column(name = "ID_EXERCICIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdExercicio() {
		return this.idExercicio;
	}

	public void setIdExercicio(Long idExercicio) {
		this.idExercicio = idExercicio;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PROFESSOR")
	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	@OneToOne
	@JoinColumn(name = "MUSICA")
	public Musica getMusica() {
		return this.musica;
	}

	public void setMusica(Musica musica) {
		this.musica = musica;
	}

	@Column(name = "NOME", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "NIVEL", length = 15)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	@Column(name = "WRITING_QUESTAO", length = 500)
	public String getWritingQuestao() {
		return writingQuestao;
	}

	public void setWritingQuestao(String writingQuestao) {
		this.writingQuestao = writingQuestao;
	}

	@Column(name = "VALOR_NOTA_MAXIMA", precision = 2, scale = 0)
	public int getValorNotaMaxima() {
		return this.valorNotaMaxima;
	}

	public void setValorNotaMaxima(int valorNotaMaxima) {
		this.valorNotaMaxima = valorNotaMaxima;
	}

	@Column(name = "TOTAL_POSTS", precision = 5, scale = 0)
	public Integer getTotalPosts() {
		return totalPosts;
	}

	public void setTotalPosts(Integer totalPosts) {
		this.totalPosts = totalPosts;
	}

	@Column(name = "MEDIA", precision = 2, scale = 0)
	public Byte getMedia() {
		return this.media;
	}

	public void setMedia(Byte media) {
		this.media = media;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public Set<ExercicioAluno> getExercicioAlunos() {
		return this.exercicioAlunos;
	}

	public void setExercicioAlunos(Set<ExercicioAluno> exercicioAlunos) {
		this.exercicioAlunos = exercicioAlunos;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public Set<Questao> getQuestoes() {
		return this.questoes;
	}

	public void setQuestoes(Set<Questao> questaos) {
		this.questoes = questaos;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public List<Imagem> getImagens() {
		return imagens;
	}

	public void setImagens(List<Imagem> imagens) {
		this.imagens = imagens;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public List<GrammarDefinicao> getGrammarDefinicoes() {
		return grammarDefinicoes;
	}

	public void setGrammarDefinicoes(List<GrammarDefinicao> grammarDefinicoes) {
		this.grammarDefinicoes = grammarDefinicoes;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public List<ReadingQuestao> getReadingQuestoes() {
		return readingQuestoes;
	}

	public void setReadingQuestoes(List<ReadingQuestao> readingQuestoes) {
		this.readingQuestoes = readingQuestoes;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicio")
	public List<PronunciationQuestao> getPronunciationQuestoes() {
		return pronunciationQuestoes;
	}

	public void setPronunciationQuestoes(List<PronunciationQuestao> pronunciationQuestoes) {
		this.pronunciationQuestoes = pronunciationQuestoes;
	}

}
