package webplatform.model.entity;
// default package

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ForumPost generated by hbm2java
 */
@Entity
@Table(name = "FORUM_POST")
public class ForumPost implements java.io.Serializable {

	private Long id;
	private Aluno aluno;
	private Exercicio exercicio;
	private Professor professor;
	private ForumPost postRespondido;
	private String texto;
	private Date dataPostagem;

	public ForumPost() {
	}

	public ForumPost(Long id) {
		this.id = id;
	}

	public ForumPost(Long id, Aluno aluno, Exercicio exercicio, Professor professor, ForumPost postRespondido,
			String texto) {
		this.id = id;
		this.aluno = aluno;
		this.exercicio = exercicio;
		this.professor = professor;
		this.postRespondido = postRespondido;
		this.texto = texto;
	}

	@Id
	@GenericGenerator(name = "FORUM_POST_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "FORUM_POST_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "FORUM_POST_SEQUENCE")
	@Column(name = "ID_FORUM_POST", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ALUNO")
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXERCICIO")
	public Exercicio getExercicio() {
		return this.exercicio;
	}

	public void setExercicio(Exercicio exercicio) {
		this.exercicio = exercicio;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PROFESSOR")
	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "POST_RESPONDIDO")
	public ForumPost getPostRespondido() {
		return postRespondido;
	}

	public void setPostRespondido(ForumPost postRespondido) {
		this.postRespondido = postRespondido;
	}

	@Column(name = "TEXTO", length = 1000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "DATA_POSTAGEM")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getDataPostagem() {
		return dataPostagem;
	}

	public void setDataPostagem(Date dataPostagem) {
		this.dataPostagem = dataPostagem;
	}

}
