package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ForumPost generated by hbm2java
 */
@Entity
@Table(name = "FORUM_POST")
public class ForumPost implements java.io.Serializable {

	private Long id;
	private ExercicioAluno exercicioAluno;
	private ForumPost forumPost;
	private String texto;

	public ForumPost() {
	}

	public ForumPost(Long id) {
		this.id = id;
	}

	public ForumPost(Long id, ExercicioAluno exercicioAluno, ForumPost forumPost, String texto) {
		this.id = id;
		this.exercicioAluno = exercicioAluno;
		this.forumPost = forumPost;
		this.texto = texto;
	}

	@Id
	@GenericGenerator(name = "FORUM_POST_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "FORUM_POST_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "FORUM_POST_SEQUENCE")
	@Column(name = "ID_FORUM_POST", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXERCICIO_ALUNO")
	public ExercicioAluno getExercicioAluno() {
		return this.exercicioAluno;
	}

	public void setExercicioAluno(ExercicioAluno exercicioAluno) {
		this.exercicioAluno = exercicioAluno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POST_RESPONDIDO")
	public ForumPost getForumPost() {
		return this.forumPost;
	}

	public void setForumPost(ForumPost forumPost) {
		this.forumPost = forumPost;
	}

	@Column(name = "TEXTO", length = 1000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

}
