package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GrammarResposta generated by hbm2java
 */
@Entity
@Table(name = "GRAMMAR_RESPOSTA")
public class GrammarResposta implements java.io.Serializable {

	private Long id;
	private ExercicioAluno exercicioAluno;
	private GrammarDefinicao grammarQuestaoResposta;
	private GrammarQuestao grammarQuestao;

	public GrammarResposta() {
	}

	public GrammarResposta(Long id) {
		this.id = id;
	}

	public GrammarResposta(Long id, ExercicioAluno exercicioAluno, GrammarDefinicao grammarQuestaoResposta,
			GrammarQuestao grammarQuestao) {
		this.id = id;
		this.exercicioAluno = exercicioAluno;
		this.grammarQuestaoResposta = grammarQuestaoResposta;
		this.grammarQuestao = grammarQuestao;
	}

	@Id
	@GenericGenerator(name = "GRAMMAR_RESPOSTA_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "GRAMMAR_RESPOSTA_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "GRAMMAR_RESPOSTA_SEQUENCE")
	@Column(name = "GRAMMAR_RESPOSTA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXERCICIO_ALUNO")
	public ExercicioAluno getExercicioAluno() {
		return this.exercicioAluno;
	}

	public void setExercicioAluno(ExercicioAluno exercicioAluno) {
		this.exercicioAluno = exercicioAluno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRAMMAR_QUESTAO_RESPOSTA")
	public GrammarDefinicao getGrammarQuestaoResposta() {
		return grammarQuestaoResposta;
	}

	public void setGrammarQuestaoResposta(GrammarDefinicao grammarQuestaoResposta) {
		this.grammarQuestaoResposta = grammarQuestaoResposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRAMMAR_QUESTAO")
	public GrammarQuestao getGrammarQuestao() {
		return this.grammarQuestao;
	}

	public void setGrammarQuestao(GrammarQuestao grammarQuestao) {
		this.grammarQuestao = grammarQuestao;
	}

}
