package webplatform.model.entity;
// default package

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * GrammarDefinicao generated by hbm2java
 */
@Entity
@Table(name = "GRAMMAR_DEFINICAO")
public class GrammarDefinicao implements java.io.Serializable {

	private Long id;
	private Exercicio exercicio;
	private String definicao;
	private Set<GrammarQuestao> questoes = new HashSet<GrammarQuestao>();

	public GrammarDefinicao() {
	}

	public GrammarDefinicao(Long id) {
		this.id = id;
	}

	public GrammarDefinicao(Long id, Exercicio exercicio, String definicao, Set<GrammarQuestao> questoes) {
		this.id = id;
		this.exercicio = exercicio;
		this.definicao = definicao;
		this.questoes = questoes;
	}

	@Id
	@SequenceGenerator(name = "GRAMMAR_DEFINICAO_SEQUENCE", sequenceName = "GRAMMAR_DEFINICAO_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "GRAMMAR_DEFINICAO_SEQUENCE")
	@Column(name = "ID_GRAMMAR_DEFINICAO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXERCICIO")
	public Exercicio getExercicio() {
		return this.exercicio;
	}

	public void setExercicio(Exercicio exercicio) {
		this.exercicio = exercicio;
	}

	@Column(name = "DEFINICAO", length = 500)
	public String getDefinicao() {
		return this.definicao;
	}

	public void setDefinicao(String definicao) {
		this.definicao = definicao;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "definicaoResposta")
	public Set<GrammarQuestao> getQuestoes() {
		return questoes;
	}

	public void setQuestoes(Set<GrammarQuestao> questoes) {
		this.questoes = questoes;
	}

}
