package webplatform.model.entity;

// default package
// Generated Mar 25, 2018 11:25:23 PM by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Imagem generated by hbm2java
 */
@Entity
@Table(name = "IMAGEM")
public class Imagem implements java.io.Serializable {

	private Long idImagem;
	private byte[] bytes;
	private Long idExercicio;
	private String nome;

	public Imagem() {
	}

	public Imagem(Long idImagem) {
		this.idImagem = idImagem;
	}

	public Imagem(Long idImagem, byte[] bytes, Long idExercicio, String nome) {
		this.idImagem = idImagem;
		this.bytes = bytes;
		this.idExercicio = idExercicio;
		this.nome = nome;
	}

	@Id
	@SequenceGenerator(name = "IMAGEM_SEQUENCE", sequenceName = "IMAGEM_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "IMAGEM_SEQUENCE")
	@Column(name = "ID_IMAGEM", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdImagem() {
		return this.idImagem;
	}

	public void setIdImagem(Long idImagem) {
		this.idImagem = idImagem;
	}

	@Lob
	@Column(name = "BYTES")
	public byte[] getBytes() {
		return this.bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

	@Column(name = "ID_EXERCICIO", precision = 22, scale = 0)
	public Long getIdExercicio() {
		return this.idExercicio;
	}

	public void setIdExercicio(Long idExercicio) {
		this.idExercicio = idExercicio;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
}
