package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PAIS")
public class Pais implements java.io.Serializable {

	private Long id;
	private String nome;

	public Pais() {
	}

	public Pais(Long id) {
		this.id = id;
	}

	public Pais(Long id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	@Id
	@Column(name = "ID_PAIS", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getid() {
		return this.id;
	}

	public void setid(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
