package webplatform.model.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Professor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PROFESSOR")
public class Professor implements java.io.Serializable {

	private Long id;
	private Pais pais;
	private String nome;
	private String sobrenome;
	private String email;
	private String genero;
	private String especialidade;
	private String nomeInstituicao;
	private String password;
	private Set<Convite> convites = new HashSet<Convite>();
	private Set<Aluno> alunos = new HashSet<Aluno>();
	private Set<Exercicio> exercicios = new HashSet<Exercicio>();

	public Professor() {
	}

	public Professor(Long id) {
		this.id = id;
	}

	public Professor(Long id, String nome, String email, String password, Set<Convite> convites, Set<Aluno> alunos,
			Set<Exercicio> exercicios, String sobrenome, String genero, String especialidade, String nomeInstituicao,
			Pais pais) {
		this.id = id;
		this.nome = nome;
		this.email = email;
		this.password = password;
		this.convites = convites;
		this.alunos = alunos;
		this.exercicios = exercicios;
		this.sobrenome = sobrenome;
		this.genero = genero;
		this.especialidade = especialidade;
		this.nomeInstituicao = nomeInstituicao;
		this.pais = pais;
	}

	@Id
	@SequenceGenerator(name = "PROFESSOR_SEQUENCE", sequenceName = "PROFESSOR_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "PROFESSOR_SEQUENCE")
	@Column(name = "ID_PROFESSOR", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NOME", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professor")
	public Set<Convite> getConvites() {
		return this.convites;
	}

	public void setConvites(Set<Convite> convites) {
		this.convites = convites;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professor")
	public Set<Aluno> getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Set<Aluno> alunos) {
		this.alunos = alunos;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professor")
	public Set<Exercicio> getExercicios() {
		return this.exercicios;
	}

	public void setExercicios(Set<Exercicio> exercicios) {
		this.exercicios = exercicios;
	}

	@Column(name = "SOBRENOME", length = 50)
	public String getSobrenome() {
		return sobrenome;
	}

	public void setSobrenome(String sobrenome) {
		this.sobrenome = sobrenome;
	}

	@Column(name = "GENERO", length = 6)
	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "ESPECIALIDADE", length = 19)
	public String getEspecialidade() {
		return especialidade;
	}

	public void setEspecialidade(String especialidade) {
		this.especialidade = especialidade;
	}

	@Column(name = "NOME_INSTITUICAO", length = 50)
	public String getNomeInstituicao() {
		return nomeInstituicao;
	}

	public void setNomeInstituicao(String nomeInstituicao) {
		this.nomeInstituicao = nomeInstituicao;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}
}
