package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PronunciationQuestaoParte generated by hbm2java
 */
@Entity
@Table(name = "PRONUNCIATION_QUESTAO_PARTE")
public class PronunciationQuestaoParte implements java.io.Serializable {

	private Long id;
	private PronunciationQuestao pronunciationQuestao;
	private String descricao;
	private String tipo;
	private Integer sequencia;

	public PronunciationQuestaoParte() {
	}

	public PronunciationQuestaoParte(Long id) {
		this.id = id;
	}

	public PronunciationQuestaoParte(Long id, PronunciationQuestao pronunciationQuestao, String descricao, String tipo,
			Integer sequencia) {
		this.id = id;
		this.pronunciationQuestao = pronunciationQuestao;
		this.descricao = descricao;
		this.tipo = tipo;
		this.sequencia = sequencia;
	}

	@Id
	@SequenceGenerator(name = "PRONUNC_QUESTAO_PARTE_SEQUENCE", sequenceName = "PRONUNC_QUESTAO_PARTE_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "PRONUNC_QUESTAO_PARTE_SEQUENCE")
	@Column(name = "ID_PRONUNCIATION_QUESTAO_PARTE", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QUESTAO")
	public PronunciationQuestao getPronunciationQuestao() {
		return this.pronunciationQuestao;
	}

	public void setPronunciationQuestao(PronunciationQuestao pronunciationQuestao) {
		this.pronunciationQuestao = pronunciationQuestao;
	}

	@Column(name = "DESCRICAO", length = 500)
	public String getDescricao() {
		return this.descricao;
	}

	@Column(name = "TIPO", length = 8)
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "SEQUENCIA", precision = 2, scale = 0)
	public Integer getSequencia() {
		return sequencia;
	}

	public void setSequencia(Integer sequencia) {
		this.sequencia = sequencia;
	}

}
