package webplatform.model.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Questao generated by hbm2java
 */
@Entity
@Table(name = "QUESTAO")
public class Questao implements java.io.Serializable {

	private Long idQuestao;
	private Exercicio exercicio;
	private String pergunta;
	private int valorNota;
	private Set<Alternativa> alternativas = new HashSet<Alternativa>();
	private Set<ExercicioAlunoResposta> exercicioAlunoRespostas = new HashSet<ExercicioAlunoResposta>();

	public Questao() {
	}

	public Questao(Long idQuestao) {
		this.idQuestao = idQuestao;
	}

	public Questao(Long idQuestao, Exercicio exercicio, String pergunta, int valorNota, Set<Alternativa> alternativas,
			Set<ExercicioAlunoResposta> exercicioAlunoRespostas) {
		this.idQuestao = idQuestao;
		this.exercicio = exercicio;
		this.pergunta = pergunta;
		this.valorNota = valorNota;
		this.alternativas = alternativas;
		this.exercicioAlunoRespostas = exercicioAlunoRespostas;
	}

	@Id
	@SequenceGenerator(name = "QUESTAO_SEQUENCE", sequenceName = "QUESTAO_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "QUESTAO_SEQUENCE")
	@Column(name = "ID_QUESTAO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdQuestao() {
		return this.idQuestao;
	}

	public void setIdQuestao(Long idQuestao) {
		this.idQuestao = idQuestao;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXERCICIO")
	public Exercicio getExercicio() {
		return this.exercicio;
	}

	public void setExercicio(Exercicio exercicio) {
		this.exercicio = exercicio;
	}

	@Column(name = "PERGUNTA", length = 100)
	public String getPergunta() {
		return this.pergunta;
	}

	public void setPergunta(String pergunta) {
		this.pergunta = pergunta;
	}

	@Column(name = "VALOR_NOTA", precision = 2, scale = 0)
	public int getValorNota() {
		return this.valorNota;
	}

	public void setValorNota(int valorNota) {
		this.valorNota = valorNota;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questao")
	public Set<Alternativa> getAlternativas() {
		return this.alternativas;
	}

	public void setAlternativas(Set<Alternativa> alternativas) {
		this.alternativas = alternativas;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questao")
	public Set<ExercicioAlunoResposta> getExercicioAlunoRespostas() {
		return this.exercicioAlunoRespostas;
	}

	public void setExercicioAlunoRespostas(Set<ExercicioAlunoResposta> exercicioAlunoRespostas) {
		this.exercicioAlunoRespostas = exercicioAlunoRespostas;
	}

}
