package webplatform.model.entity;
// default package

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ReadingQuestao generated by hbm2java
 */
@Entity
@Table(name = "READING_QUESTAO")
public class ReadingQuestao implements java.io.Serializable {

	private Long id;
	private Exercicio exercicio;
	private String pergunta;
	private Set<ReadingAlternativa> readingAlternativas = new HashSet<ReadingAlternativa>();

	public ReadingQuestao() {
	}

	public ReadingQuestao(Long id) {
		this.id = id;
	}

	public ReadingQuestao(Long id, Exercicio exercicio, String pergunta, Set<ReadingAlternativa> readingAlternativas) {
		this.id = id;
		this.exercicio = exercicio;
		this.pergunta = pergunta;
		this.readingAlternativas = readingAlternativas;
	}

	@Id
	@SequenceGenerator(name = "READING_QUESTAO_SEQUENCE", sequenceName = "READING_QUESTAO_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "READING_QUESTAO_SEQUENCE")
	@Column(name = "ID_READING_QUESTAO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXERCICIO")
	public Exercicio getExercicio() {
		return this.exercicio;
	}

	public void setExercicio(Exercicio exercicio) {
		this.exercicio = exercicio;
	}

	@Column(name = "PERGUNTA", length = 500)
	public String getPergunta() {
		return this.pergunta;
	}

	public void setPergunta(String pergunta) {
		this.pergunta = pergunta;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questao")
	public Set<ReadingAlternativa> getReadingAlternativas() {
		return readingAlternativas;
	}

	public void setReadingAlternativas(Set<ReadingAlternativa> readingAlternativas) {
		this.readingAlternativas = readingAlternativas;
	}

}
