package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * ReadingAlternativa generated by hbm2java
 */
@Entity
@Table(name = "READING_ALTERNATIVA")
public class ReadingAlternativa implements java.io.Serializable {

	private Long id;
	private ReadingQuestao questao;
	private String descricao;
	private Boolean correta;

	public ReadingAlternativa() {
	}

	public ReadingAlternativa(Long id) {
		this.id = id;
	}

	public ReadingAlternativa(Long id, ReadingQuestao readingQuestao, String descricao, Boolean correta) {
		this.id = id;
		this.questao = readingQuestao;
		this.descricao = descricao;
		this.correta = correta;
	}

	@Id
	@SequenceGenerator(name = "READING_ALTERNATIVA_SEQUENCE", sequenceName = "READING_ALTERNATIVA_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "READING_ALTERNATIVA_SEQUENCE")
	@Column(name = "ID_READING_ALTERNATIVA", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QUESTAO")
	public ReadingQuestao getQuestao() {
		return questao;
	}

	public void setQuestao(ReadingQuestao questao) {
		this.questao = questao;
	}

	@Column(name = "DESCRICAO", length = 500)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "CORRETA")
	@Type(type = "yes_no")
	public Boolean getCorreta() {
		return correta;
	}

	public void setCorreta(Boolean correta) {
		this.correta = correta;
	}

}
