package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

/**
 * ReadingAlternativa generated by hbm2java
 */
@Entity
@Table(name = "READING_ALTERNATIVA")
public class ReadingAlternativa implements java.io.Serializable {

	private Long id;
	private ReadingQuestao questao;
	private String descricao;
	private Boolean correta;
	private Integer sequencia;

	public ReadingAlternativa() {
	}

	public ReadingAlternativa(Long id) {
		this.id = id;
	}

	public ReadingAlternativa(Long id, ReadingQuestao readingQuestao, String descricao, Boolean correta,
			Integer sequencia) {
		this.id = id;
		this.questao = readingQuestao;
		this.descricao = descricao;
		this.correta = correta;
		this.sequencia = sequencia;
	}

	@Id
	@GenericGenerator(name = "READING_ALTERNATIVA_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "READING_ALTERNATIVA_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "READING_ALTERNATIVA_SEQUENCE")
	@Column(name = "ID_READING_ALTERNATIVA", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QUESTAO")
	public ReadingQuestao getQuestao() {
		return questao;
	}

	public void setQuestao(ReadingQuestao questao) {
		this.questao = questao;
	}

	@Column(name = "DESCRICAO", length = 500)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "CORRETA")
	@Type(type = "yes_no")
	public Boolean getCorreta() {
		return correta;
	}

	public void setCorreta(Boolean correta) {
		this.correta = correta;
	}

	@Column(name = "SEQUENCIA", precision = 2, scale = 0)
	public Integer getSequencia() {
		return sequencia;
	}

	public void setSequencia(Integer sequencia) {
		this.sequencia = sequencia;
	}

}
