package webplatform.model.entity;
// default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * VocabularyResposta generated by hbm2java
 */
@Entity
@Table(name = "VOCABULARY_RESPOSTA")
public class VocabularyResposta implements java.io.Serializable {

	private Long id;
	private ExercicioAluno exercicioAluno;
	private Imagem imagem;
	private String imagemResposta;

	public VocabularyResposta() {
	}

	public VocabularyResposta(Long id) {
		this.id = id;
	}

	public VocabularyResposta(Long id, ExercicioAluno exercicioAluno, Imagem imagem, String imagemResposta) {
		this.id = id;
		this.exercicioAluno = exercicioAluno;
		this.imagem = imagem;
		this.imagemResposta = imagemResposta;
	}

	@Id
	@GenericGenerator(name = "VOCABULARY_RESPOSTA_SEQUENCE", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "VOCABULARY_RESPOSTA_SEQUENCE"),
			@Parameter(name = "initial_value", value = "1"), @Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "VOCABULARY_RESPOSTA_SEQUENCE")
	@Column(name = "VOCABULARY_RESPOSTA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXERCICIO_ALUNO")
	public ExercicioAluno getExercicioAluno() {
		return this.exercicioAluno;
	}

	public void setExercicioAluno(ExercicioAluno exercicioAluno) {
		this.exercicioAluno = exercicioAluno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMAGEM")
	public Imagem getImagem() {
		return this.imagem;
	}

	public void setImagem(Imagem imagem) {
		this.imagem = imagem;
	}

	@Column(name = "IMAGEM_RESPOSTA", length = 50)
	public String getImagemResposta() {
		return this.imagemResposta;
	}

	public void setImagemResposta(String imagemResposta) {
		this.imagemResposta = imagemResposta;
	}

}
